@startuml

left to right direction

' Add a header with left alignment
header
Dar El Salam
endheader

' Align the header text to the left
skinparam headerAlignment left

' Custom skin parameters for use cases
skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Customer" as Customer

rectangle "Travel Trove System" {

    usecase "Sign up for an Account"
    usecase "Set up Profile"

    usecase "Browse tour packages"
    usecase "Filter search result"
    usecase "Subscribe to notifications"

    usecase "Book a tour package"
    usecase "Pay for a tour"

    usecase "Cancel a trip"
    usecase "Request a refund"
}

"Sign up for an Account" <.. "Set up Profile" : <<extend>>
"Browse tour packages" <.. "Book a tour package" : <<extend>>
"Browse tour packages" <.. "Subscribe to notifications" : <<extend>>
"Book a tour package" <.. "Filter search result" : <<extend>>
"Book a tour package" <.. "Pay for a tour" : <<include>>
"Cancel a trip" <.. "Request a refund" : <<extend>>

Customer -- "Sign up for an Account"
Customer -- "Browse tour packages"
'Customer -- "Book a tour package"
Customer -- "Cancel a trip"

@enduml