server.port: 8080

logging:
  level:
    root: INFO
    com.be-lecoingameover: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: lecoingameoverdb
      username: root
      password: password
      authentication-database: admin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5


---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongo
      port: 27017
      database: lecoingameoverdb
      username: root
      password: password
      authentication-database: admin